steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/newwavealt:$SHORT_SHA',
        '.'
      ]

  # Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/newwavealt:$SHORT_SHA'
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'newwavealt',
        '--image', 'gcr.io/$PROJECT_ID/newwavealt:$SHORT_SHA',
        '--platform', 'managed',
        '--region', 'us-west1',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - 'gcr.io/$PROJECT_ID/newwavealt:$SHORT_SHA'
